- name: Freeradius additional postgresql system packages
  when: openwisp2_radius and freeradius_sql.dialect == "postgresql"
  apt:
    name:
      - postgresql
      - freeradius-postgresql
      - libpq-dev
    state: latest
  notify: start postgresql

- name: Install psycopg2
  when: openwisp2_radius and freeradius_sql.dialect == "postgresql"
  pip:
    name: psycopg2
    state: latest
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: start postgresql

- name: start postgresql for migration
  when: openwisp2_radius and freeradius_sql.dialect == "postgresql"
  meta: flush_handlers

- name: Create freeradius database
  when: openwisp2_radius and freeradius_sql.dialect == "postgresql"
  become_user: postgres
  become: true
  postgresql_db:
    name: "{{ freeradius_sql.dbname }}"
    state: present

- name: Create freeradius database user
  when: openwisp2_radius and freeradius_sql.dialect == "postgresql"
  become_user: postgres
  become: true
  postgresql_user:
    db: "{{ freeradius_sql.dbname }}"
    name: "{{ freeradius_sql.user }}"
    password: "{{ freeradius_sql.password }}"
    priv: ALL
