- name: create "{{ openwisp2_path }}/public_html"
  file:
    path: "{{ openwisp2_path }}/public_html"
    state: directory
    mode: 0775

- name: create "{{ openwisp2_path }}/ssl"
  file:
    path: "{{ openwisp2_path }}/ssl"
    state: directory
    mode: 0770

- name: create SSL cert if not exists yet
  command: >
    openssl req -new -nodes -x509 \
    -subj "/C={{ openwisp2_ssl_country }}/ST={{ openwisp2_ssl_state }}/L={{ openwisp2_ssl_locality }}/O={{ openwisp2_ssl_organization }}/CN={{ openwisp2_ssl_common_name }}" \
    -days 3650 \
    -keyout {{ openwisp2_ssl_key }} \
    -out {{ openwisp2_ssl_cert }} \
    -extensions v3_ca creates={{ openwisp2_ssl_cert }}
  args:
    warn: False
  notify: restart nginx

- name: Copy SSL cert to be added to trusted Cert (for freeradius)
  copy:
    src: "{{ openwisp2_ssl_cert }}"
    dest: /usr/local/share/ca-certificates/openwisp-ssl-server.crt
    remote_src: yes
  when: ansible_os_family == 'Debian'
  notify: update-ca-certificates

- name: disable default nginx configuration
  file:
   path: "/etc/nginx/sites-enabled/default"
   state: absent

- name: nginx site available
  template:
    src: nginx.j2
    dest: "/etc/nginx/sites-available/{{ inventory_hostname }}"
    mode: 0644
  notify: restart nginx
  when: ansible_os_family == 'Debian'

- name: nginx site enabled
  file:
    src: "/etc/nginx/sites-available/{{ inventory_hostname }}"
    dest: "/etc/nginx/sites-enabled/{{ inventory_hostname }}"
    state: link
  notify: restart nginx
  when: ansible_os_family == 'Debian'
